navibridger_handcraft:
  config_path: "../model_weights/navibridger_handcraft.yaml"
  ckpt_path: "../model_weights/navibridger_handcraft.pth"

navibridger_noise:
  config_path: "../model_weights/navibridger_noise.yaml"
  ckpt_path: "../model_weights/navibridger_noise.pth"

navibridger_cvae:
  config_path: "../model_weights/navibridger_cvae.yaml"
  ckpt_path: "../model_weights/navibridger_cvae.pth"
cvae:
  config_path: "../model_weights/cvae.yaml"
  ckpt_path: "../model_weights/cvae.pth"